=== sisaac10/SQLNoSQLFinalProject/edexpSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="row"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="row">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="country"/>
        <xs:element ref="institute_type"/>
        <xs:element ref="direct_expenditure_type"/>
        <xs:element ref="Year1995"/>
        <xs:element ref="Year2000"/>
        <xs:element ref="Year2005"/>
        <xs:element ref="Year2009"/>
        <xs:element ref="Year2010"/>
        <xs:element ref="Year2011"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="country" type="xs:string"/>
  <xs:element name="institute_type" type="xs:string"/>
  <xs:element name="direct_expenditure_type" type="xs:NCName"/>
  <xs:element name="Year1995" type="xs:string"/>
  <xs:element name="Year2000" type="xs:string"/>
  <xs:element name="Year2005" type="xs:string"/>
  <xs:element name="Year2009" type="xs:string"/>
  <xs:element name="Year2010" type="xs:string"/>
  <xs:element name="Year2011" type="xs:string"/>
</xs:schema>

=== sisaac10/SQLNoSQLFinalProject/edexpense.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="edexpStyle.xsl" ?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="edexpSchema.xsd">
    <row>
        <country>OECD Average</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>4.9</Year1995>
        <Year2000>4.9</Year2000>
        <Year2005>5</Year2005>
        <Year2009>5.4</Year2009>
        <Year2010>5.4</Year2010>
        <Year2011>5.3</Year2011>
    </row>
    <row>
        <country>Australia</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>4.5</Year1995>
        <Year2000>4.6</Year2000>
        <Year2005>4.3</Year2005>
        <Year2009>4.5</Year2009>
        <Year2010>4.6</Year2010>
        <Year2011>4.3</Year2011>
    </row>
    <row>
        <country>Austria</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>5.3</Year1995>
        <Year2000>5.4</Year2000>
        <Year2005>5.2</Year2005>
        <Year2009>5.7</Year2009>
        <Year2010>5.6</Year2010>
        <Year2011>5.5</Year2011>
    </row>
    <row>
        <country>Belgium</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>5</Year1995>
        <Year2000>5.1</Year2000>
        <Year2005>5.8</Year2005>
        <Year2009>6.4</Year2009>
        <Year2010>6.4</Year2010>
        <Year2011>6.4</Year2011>
    </row>
    <row>
        <country>Canada</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>5.8</Year1995>
        <Year2000>5.2</Year2000>
        <Year2005>4.8</Year2005>
        <Year2009>5</Year2009>
        <Year2010>5.2</Year2010>
        <Year2011></Year2011>
    </row>
    <row>
        <country>Chile</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995></Year1995>
        <Year2000>4.2</Year2000>
        <Year2005>3.3</Year2005>
        <Year2009>4.1</Year2009>
        <Year2010>4.3</Year2010>
        <Year2011>3.9</Year2011>
    </row>
    <row>
        <country>Czech Republic</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>4.8</Year1995>
        <Year2000>4.2</Year2000>
        <Year2005>4.1</Year2005>
        <Year2009>4.2</Year2009>
        <Year2010>4.1</Year2010>
        <Year2011>4.4</Year2011>
    </row>
    <row>
        <country>Denmark</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>6.5</Year1995>
        <Year2000>6.4</Year2000>
        <Year2005>6.8</Year2005>
        <Year2009>7.5</Year2009>
        <Year2010>7.6</Year2010>
        <Year2011>7.5</Year2011>
    </row>
    <row>
        <country>Estonia</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995></Year1995>
        <Year2000></Year2000>
        <Year2005>4.7</Year2005>
        <Year2009>5.9</Year2009>
        <Year2010>5.6</Year2010>
        <Year2011>5.2</Year2011>
    </row>
    <row>
        <country>Finland</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>6.6</Year1995>
        <Year2000>5.5</Year2000>
        <Year2005>5.9</Year2005>
        <Year2009>6.3</Year2009>
        <Year2010>6.4</Year2010>
        <Year2011>6.3</Year2011>
    </row>
    <row>
        <country>France</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>5.8</Year1995>
        <Year2000>5.7</Year2000>
        <Year2005>5.6</Year2005>
        <Year2009>5.8</Year2009>
        <Year2010>5.8</Year2010>
        <Year2011>5.6</Year2011>
    </row>
    <row>
        <country>Germany</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>4.5</Year1995>
        <Year2000>4.3</Year2000>
        <Year2005>4.2</Year2005>
        <Year2009>4.5</Year2009>
        <Year2010></Year2010>
        <Year2011>4.4</Year2011>
    </row>
    <row>
        <country>Greece</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>3.7</Year1995>
        <Year2000>3.7</Year2000>
        <Year2005>4</Year2005>
        <Year2009></Year2009>
        <Year2010></Year2010>
        <Year2011></Year2011>
    </row>
    <row>
        <country>Hungary</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>4.9</Year1995>
        <Year2000>4.4</Year2000>
        <Year2005>5.1</Year2005>
        <Year2009>4.8</Year2009>
        <Year2010>4.6</Year2010>
        <Year2011>4.4</Year2011>
    </row>
    <row>
        <country>Iceland</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>4.5</Year1995>
        <Year2000>5.7</Year2000>
        <Year2005>7.2</Year2005>
        <Year2009>7.3</Year2009>
        <Year2010>7</Year2010>
        <Year2011>6.9</Year2011>
    </row>
    <row>
        <country>Ireland</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>4.7</Year1995>
        <Year2000>4.1</Year2000>
        <Year2005>4.3</Year2005>
        <Year2009>6</Year2009>
        <Year2010>6</Year2010>
        <Year2011>5.7</Year2011>
    </row>
    <row>
        <country>Israel</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995></Year1995>
        <Year2000>6.6</Year2000>
        <Year2005>6.2</Year2005>
        <Year2009>5.8</Year2009>
        <Year2010>5.9</Year2010>
        <Year2011>5.6</Year2011>
    </row>
    <row>
        <country>Italy</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>4.5</Year1995>
        <Year2000>4.5</Year2000>
        <Year2005>4.3</Year2005>
        <Year2009>4.5</Year2009>
        <Year2010>4.3</Year2010>
        <Year2011>4.2</Year2011>
    </row>
    <row>
        <country>Japan</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>3.6</Year1995>
        <Year2000>3.5</Year2000>
        <Year2005>3.4</Year2005>
        <Year2009>3.6</Year2009>
        <Year2010>3.6</Year2010>
        <Year2011>3.6</Year2011>
    </row>
    <row>
        <country>Korea, Republic of</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>3.6</Year1995>
        <Year2000>4.3</Year2000>
        <Year2005>4.3</Year2005>
        <Year2009>4.9</Year2009>
        <Year2010>4.8</Year2010>
        <Year2011>4.9</Year2011>
    </row>
    <row>
        <country>Luxembourg</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>4.3</Year1995>
        <Year2000></Year2000>
        <Year2005></Year2005>
        <Year2009></Year2009>
        <Year2010></Year2010>
        <Year2011></Year2011>
    </row>
    <row>
        <country>Mexico</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>4.6</Year1995>
        <Year2000>4.7</Year2000>
        <Year2005>5.3</Year2005>
        <Year2009>5</Year2009>
        <Year2010>5.1</Year2010>
        <Year2011>5</Year2011>
    </row>
    <row>
        <country>Netherlands</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>4.6</Year1995>
        <Year2000>4.3</Year2000>
        <Year2005>4.6</Year2005>
        <Year2009>5.3</Year2009>
        <Year2010>5.4</Year2010>
        <Year2011>5.3</Year2011>
    </row>
    <row>
        <country>New Zealand</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>5.3</Year1995>
        <Year2000>5.8</Year2000>
        <Year2005>5.2</Year2005>
        <Year2009>6.1</Year2009>
        <Year2010>6</Year2010>
        <Year2011>6.3</Year2011>
    </row>
    <row>
        <country>Norway</country>
        <institute_type>All Institutions </institute_type>
        <direct_expenditure_type>Public</direct_expenditure_type>
        <Year1995>6.8</Year1995>
        <Year2000>5.8</Year2000>
        <Year2005>5.7</Year2005>
        <Year2009>6.1</Year2009>
        <Year2010>7.5</Year2010>
        <Year2011>7.3</Year2011>
    </row>
    <row>
        <country>Poland</country>
