=== sisaac10/SQLNoSQLFinalProject/happySchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="row"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="row">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Country"/>
        <xs:element ref="Region"/>
        <xs:element ref="Happiness_Rank"/>
        <xs:element ref="Happiness_Score"/>
        <xs:element ref="Lower_Confidence_Interval"/>
        <xs:element ref="Upper_Confidence_Interval"/>
        <xs:element ref="Economy__GDP_per_Capita_"/>
        <xs:element ref="Family"/>
        <xs:element ref="Health__Life_Expectancy_"/>
        <xs:element ref="Freedom"/>
        <xs:element ref="Trust__Government_Corruption_"/>
        <xs:element ref="Generosity"/>
        <xs:element ref="Dystopia_Residual"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Country" type="xs:string"/>
  <xs:element name="Region" type="xs:string"/>
  <xs:element name="Happiness_Rank" type="xs:integer"/>
  <xs:element name="Happiness_Score" type="xs:decimal"/>
  <xs:element name="Lower_Confidence_Interval" type="xs:decimal"/>
  <xs:element name="Upper_Confidence_Interval" type="xs:decimal"/>
  <xs:element name="Economy__GDP_per_Capita_" type="xs:decimal"/>
  <xs:element name="Family" type="xs:decimal"/>
  <xs:element name="Health__Life_Expectancy_" type="xs:decimal"/>
  <xs:element name="Freedom" type="xs:decimal"/>
  <xs:element name="Trust__Government_Corruption_" type="xs:decimal"/>
  <xs:element name="Generosity" type="xs:decimal"/>
  <xs:element name="Dystopia_Residual" type="xs:decimal"/>
</xs:schema>

=== sisaac10/SQLNoSQLFinalProject/happiness.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="happyStyle.xsl" ?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="happySchema.xsd">
    <row>
        <Country>Denmark</Country>
        <Region>Western Europe</Region>
        <Happiness_Rank>1</Happiness_Rank>
        <Happiness_Score>7.526</Happiness_Score>
        <Lower_Confidence_Interval>7.46</Lower_Confidence_Interval>
        <Upper_Confidence_Interval>7.592</Upper_Confidence_Interval>
        <Economy__GDP_per_Capita_>1.44178</Economy__GDP_per_Capita_>
        <Family>1.16374</Family>
        <Health__Life_Expectancy_>0.79504</Health__Life_Expectancy_>
        <Freedom>0.57941</Freedom>
        <Trust__Government_Corruption_>0.44453</Trust__Government_Corruption_>
        <Generosity>0.36171</Generosity>
        <Dystopia_Residual>2.73939</Dystopia_Residual>
    </row>
    <row>
        <Country>Switzerland</Country>
        <Region>Western Europe</Region>
        <Happiness_Rank>2</Happiness_Rank>
        <Happiness_Score>7.509</Happiness_Score>
        <Lower_Confidence_Interval>7.428</Lower_Confidence_Interval>
        <Upper_Confidence_Interval>7.59</Upper_Confidence_Interval>
        <Economy__GDP_per_Capita_>1.52733</Economy__GDP_per_Capita_>
        <Family>1.14524</Family>
        <Health__Life_Expectancy_>0.86303</Health__Life_Expectancy_>
        <Freedom>0.58557</Freedom>
        <Trust__Government_Corruption_>0.41203</Trust__Government_Corruption_>
        <Generosity>0.28083</Generosity>
        <Dystopia_Residual>2.69463</Dystopia_Residual>
    </row>
    <row>
        <Country>Iceland</Country>
        <Region>Western Europe</Region>
        <Happiness_Rank>3</Happiness_Rank>
        <Happiness_Score>7.501</Happiness_Score>
        <Lower_Confidence_Interval>7.333</Lower_Confidence_Interval>
        <Upper_Confidence_Interval>7.669</Upper_Confidence_Interval>
        <Economy__GDP_per_Capita_>1.42666</Economy__GDP_per_Capita_>
        <Family>1.18326</Family>
        <Health__Life_Expectancy_>0.86733</Health__Life_Expectancy_>
        <Freedom>0.56624</Freedom>
        <Trust__Government_Corruption_>0.14975</Trust__Government_Corruption_>
        <Generosity>0.47678</Generosity>
        <Dystopia_Residual>2.83137</Dystopia_Residual>
    </row>
    <row>
        <Country>Norway</Country>
        <Region>Western Europe</Region>
        <Happiness_Rank>4</Happiness_Rank>
        <Happiness_Score>7.498</Happiness_Score>
        <Lower_Confidence_Interval>7.421</Lower_Confidence_Interval>
        <Upper_Confidence_Interval>7.575</Upper_Confidence_Interval>
        <Economy__GDP_per_Capita_>1.57744</Economy__GDP_per_Capita_>
        <Family>1.1269</Family>
        <Health__Life_Expectancy_>0.79579</Health__Life_Expectancy_>
        <Freedom>0.59609</Freedom>
        <Trust__Government_Corruption_>0.35776</Trust__Government_Corruption_>
        <Generosity>0.37895</Generosity>
        <Dystopia_Residual>2.66465</Dystopia_Residual>
    </row>
    <row>
        <Country>Finland</Country>
        <Region>Western Europe</Region>
        <Happiness_Rank>5</Happiness_Rank>
        <Happiness_Score>7.413</Happiness_Score>
        <Lower_Confidence_Interval>7.351</Lower_Confidence_Interval>
        <Upper_Confidence_Interval>7.475</Upper_Confidence_Interval>
        <Economy__GDP_per_Capita_>1.40598</Economy__GDP_per_Capita_>
        <Family>1.13464</Family>
        <Health__Life_Expectancy_>0.81091</Health__Life_Expectancy_>
        <Freedom>0.57104</Freedom>
        <Trust__Government_Corruption_>0.41004</Trust__Government_Corruption_>
        <Generosity>0.25492</Generosity>
        <Dystopia_Residual>2.82596</Dystopia_Residual>
    </row>
    <row>
        <Country>Canada</Country>
        <Region>North America</Region>
        <Happiness_Rank>6</Happiness_Rank>
        <Happiness_Score>7.404</Happiness_Score>
        <Lower_Confidence_Interval>7.335</Lower_Confidence_Interval>
        <Upper_Confidence_Interval>7.473</Upper_Confidence_Interval>
        <Economy__GDP_per_Capita_>1.44015</Economy__GDP_per_Capita_>
        <Family>1.0961</Family>
        <Health__Life_Expectancy_>0.8276</Health__Life_Expectancy_>
        <Freedom>0.5737</Freedom>
        <Trust__Government_Corruption_>0.31329</Trust__Government_Corruption_>
        <Generosity>0.44834</Generosity>
        <Dystopia_Residual>2.70485</Dystopia_Residual>
    </row>
    <row>
        <Country>Netherlands</Country>
        <Region>Western Europe</Region>
        <Happiness_Rank>7</Happiness_Rank>
        <Happiness_Score>7.339</Happiness_Score>
        <Lower_Confidence_Interval>7.284</Lower_Confidence_Interval>
        <Upper_Confidence_Interval>7.394</Upper_Confidence_Interval>
        <Economy__GDP_per_Capita_>1.46468</Economy__GDP_per_Capita_>
        <Family>1.02912</Family>
        <Health__Life_Expectancy_>0.81231</Health__Life_Expectancy_>
        <Freedom>0.55211</Freedom>
        <Trust__Government_Corruption_>0.29927</Trust__Government_Corruption_>
        <Generosity>0.47416</Generosity>
        <Dystopia_Residual>2.70749</Dystopia_Residual>
    </row>
    <row>
        <Country>New Zealand</Country>
        <Region>Australia and New Zealand</Region>
        <Happiness_Rank>8</Happiness_Rank>
        <Happiness_Score>7.334</Happiness_Score>
        <Lower_Confidence_Interval>7.264</Lower_Confidence_Interval>
        <Upper_Confidence_Interval>7.404</Upper_Confidence_Interval>
        <Economy__GDP_per_Capita_>1.36066</Economy__GDP_per_Capita_>
        <Family>1.17278</Family>
        <Health__Life_Expectancy_>0.83096</Health__Life_Expectancy_>
        <Freedom>0.58147</Freedom>
        <Trust__Government_Corruption_>0.41904</Trust__Government_Corruption_>
        <Generosity>0.49401</Generosity>
        <Dystopia_Residual>2.47553</Dystopia_Residual>
    </row>
    <row>
        <Country>Australia</Country>
        <Region>Australia and New Zealand</Region>
        <Happiness_Rank>9</Happiness_Rank>
        <Happiness_Score>7.313</Happiness_Score>
        <Lower_Confidence_Interval>7.241</Lower_Confidence_Interval>
        <Upper_Confidence_Interval>7.385</Upper_Confidence_Interval>
        <Economy__GDP_per_Capita_>1.44443</Economy__GDP_per_Capita_>
        <Family>1.10476</Family>
        <Health__Life_Expectancy_>0.8512</Health__Life_Expectancy_>
        <Freedom>0.56837</Freedom>
        <Trust__Government_Corruption_>0.32331</Trust__Government_Corruption_>
        <Generosity>0.47407</Generosity>
        <Dystopia_Residual>2.5465</Dystopia_Residual>
    </row>
    <row>
        <Country>Sweden</Country>
        <Region>Western Europe</Region>
        <Happiness_Rank>10</Happiness_Rank>
        <Happiness_Score>7.291</Happiness_Score>
        <Lower_Confidence_Interval>7.227</Lower_Confidence_Interval>
        <Upper_Confidence_Interval>7.355</Upper_Confidence_Interval>
        <Economy__GDP_per_Capita_>1.45181</Economy__GDP_per_Capita_>
        <Family>1.08764</Family>
        <Health__Life_Expectancy_>0.83121</Health__Life_Expectancy_>
        <Freedom>0.58218</Freedom>
        <Trust__Government_Corruption_>0.40867</Trust__Government_Corruption_>
        <Generosity>0.38254</Generosity>
        <Dystopia_Residual>2.54734</Dystopia_Residual>
    </row>
    <row>
        <Country>Israel</Country>
        <Region>Middle East and Northern Africa</Region>
        <Happiness_Rank>11</Happiness_Rank>
        <Happiness_Score>7.267</Happiness_Score>
        <Lower_Confidence_Interval>7.199</Lower_Confidence_Interval>
        <Upper_Confidence_Interval>7.335</Upper_Confidence_Interval>
        <Economy__GDP_per_Capita_>1.33766</Economy__GDP_per_Capita_>
        <Family>0.99537</Family>
        <Health__Life_Expectancy_>0.84917</Health__Life_Expectancy_>
        <Freedom>0.36432</Freedom>
        <Trust__Government_Corruption_>0.08728</Trust__Government_Corruption_>
        <Generosity>0.32288</Generosity>
        <Dystopia_Residual>3.31029</Dystopia_Residual>
    </row>
    <row>
        <Country>Austria</Country>
        <Region>Western Europe</Region>
        <Happiness_Rank>12</Happiness_Rank>
        <Happiness_Score>7.119</Happiness_Score>
        <Lower_Confidence_Interval>7.045</Lower_Confidence_Interval>
        <Upper_Confidence_Interval>7.193</Upper_Confidence_Interval>
        <Economy__GDP_per_Capita_>1.45038</Economy__GDP_per_Capita_>
        <Family>1.08383</Family>
        <Health__Life_Expectancy_>0.80565</Health__Life_Expectancy_>
        <Freedom>0.54355</Freedom>
        <Trust__Government_Corruption_>0.21348</Trust__Government_Corruption_>
        <Generosity>0.32865</Generosity>
        <Dystopia_Residual>2.69343</Dystopia_Residual>
    </row>
    <row>
        <Country>United States</Country>
        <Region>North America</Region>
        <Happiness_Rank>13</Happiness_Rank>
        <Happiness_Score>7.104</Happiness_Score>
        <Lower_Confidence_Interval>7.02</Lower_Confidence_Interval>
        <Upper_Confidence_Interval>7.188</Upper_Confidence_Interval>
        <Economy__GDP_per_Capita_>1.50796</Economy__GDP_per_Capita_>
        <Family>1.04782</Family>
        <Health__Life_Expectancy_>0.779</Health__Life_Expectancy_>
        <Freedom>0.48163</Freedom>
        <Trust__Government_Corruption_>0.14868</Trust__Government_Corruption_>
        <Generosity>0.41077</Generosity>
        <Dystopia_Residual>2.72782</Dystopia_Residual>
    </row>
    <row>
        <Country>Costa Rica</Country>
        <Region>Latin America and Caribbean</Region>
        <Happiness_Rank>14</Happiness_Rank>
        <Happiness_Score>7.087</Happiness_Score>
        <Lower_Confidence_Interval>6.999</Lower_Confidence_Interval>
        <Upper_Confidence_Interval>7.175</Upper_Confidence_Interval>
